version: "3.9"
services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
